FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy the rest of the application code
COPY . .

# Expose port for development server
EXPOSE 4200

# Start development server with host set to 0.0.0.0 to allow external connections
CMD ["npm", "start", "--", "--host", "0.0.0.0"]