version: '3.8'

services:
  ent-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - ent-network

networks:
  ent-network:
    driver: bridge